version: '3'  
services:
  postgres:
    image: initpsql:latest
    network_mode: bridge
    container_name: my_postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5234:5432
    environment:
         - POSTGRES_PASSWORD=111261
         - POSTGRES_USER=nikittossii
         - POSTGRES_DB=shop
    restart: unless-stopped
# APP*****************************************

  springbootapp:
    image: spring-docker
    network_mode: bridge
    container_name: spring-docker
    expose:
      - 8080
    ports:
      - 8081:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data:
